/**
 * Build-time codegen: inline the skill's markdown modules into a committed TS
 * module so the deployed serverless function never reads the sibling ../skill
 * directory at runtime (which isn't present on Vercel's filesystem).
 *
 * Run via `bun run gen` (also runs automatically in `prebuild`). Reads
 * ../skill/*.md and writes app/skill-data.generated.ts.
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const SKILL_DIR = join(import.meta.dir, "..", "..", "skill");
const OUT = join(import.meta.dir, "..", "app", "skill-data.generated.ts");

if (!existsSync(SKILL_DIR)) {
  console.error(`!! skill dir not found at ${SKILL_DIR} — leaving existing generated file in place`);
  process.exit(0);
}

const docs: { file: string; text: string }[] = [];
for (const file of readdirSync(SKILL_DIR).sort()) {
  if (!file.endsWith(".md")) continue;
  docs.push({ file, text: readFileSync(join(SKILL_DIR, file), "utf8") });
}

const skillMd = docs.find((d) => d.file === "SKILL.md")?.text ?? "";

const banner = `// AUTO-GENERATED by scripts/gen-skill-data.ts — do not edit.\n// Source: ../skill/*.md. Regenerate with \`bun run gen\`.\n`;
const body =
  `export const SKILL_MD = ${JSON.stringify(skillMd)};\n\n` +
  `export const SKILL_DOCS: { file: string; text: string }[] = ${JSON.stringify(docs)};\n`;

writeFileSync(OUT, banner + "\n" + body);
console.log(`✓ wrote ${OUT} — ${docs.length} modules, SKILL.md ${skillMd.length} chars`);
